services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-api-gateway
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
