version: '3.8'

services:
  glide-api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glide-api-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - glide-network

  # Optional: Add a reverse proxy for SSL termination
  nginx:
    image: nginx:alpine
    container_name: glide-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - glide-api-gateway
    networks:
      - glide-network

networks:
  glide-network:
    driver: bridge

volumes:
  ssl_data: