version: '3.8'

services:
  glide-api-gateway:
    image: node:18-alpine
    container_name: glide-api-gateway
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "
      apk add --no-cache curl wget &&
      
      echo 'ewogICJuYW1lIjogImdsaWRlLWFwaS1nYXRld2F5IiwKICAidmVyc2lvbiI6ICIxLjAuMCIsCiAgIm1haW4iOiAiaW5kZXguanMiLAogICJkZXBlbmRlbmNpZXMiOiB7CiAgICAiZXhwcmVzcyI6ICJeNC4xOC4yIiwKICAgICJjb3JzIjogIl4yLjguNSIsCiAgICAiZXhwcmVzcy1yYXRlLWxpbWl0IjogIl42LjcuMCIsCiAgICAiYXhpb3MiOiAiXjEuNC4wIgogIH0KfQ==' | base64 -d > package.json &&
      
      echo 'Y29uc3QgZXhwcmVzcyA9IHJlcXVpcmUoJ2V4cHJlc3MnKTsKY29uc3QgY29ycyA9IHJlcXVpcmUoJ2NvcnMnKTsKY29uc3QgcmF0ZUxpbWl0ID0gcmVxdWlyZSgnZXhwcmVzcy1yYXRlLWxpbWl0Jyk7CmNvbnN0IGF4aW9zID0gcmVxdWlyZSgnYXhpb3MnKTsKCmNvbnN0IGFwcCA9IGV4cHJlc3MoKTsKY29uc3QgcG9ydCA9IHByb2Nlc3MuZW52LlBPUlQgfHwgMzAwMDsKCmFwcC51c2UoY29ycyh7IG9yaWdpbjogcHJvY2Vzcy5lbnYuQ09SU19PUklHSU4gfHwgJyonIH0pKTsKYXBwLnVzZShleHByZXNzLmpzb24oKSk7Cgpjb25zdCBsaW1pdGVyID0gcmF0ZUxpbWl0KHsKICB3aW5kb3dNczogKHByb2Nlc3MuZW52LlJBVEVfTElNSVRfV0lORE9XIHx8IDE1KSAqIDYwICogMTAwMCwKICBtYXg6IHByb2Nlc3MuZW52LlJBVEVfTElNSVRfTUFYIHx8IDEwMAp9KTsKYXBwLnVzZShsaW1pdGVyKTsKCmFwcC5nZXQoJy9oZWFsdGgnLCAocmVxLCByZXMpID0+IHsKICByZXMuanNvbih7IAogICAgc3RhdHVzOiAnaGVhbHRoeScsIAogICAgdGltZXN0YW1wOiBuZXcgRGF0ZSgpLnRvSVNPU3RyaW5nKCksCiAgICB2ZXJzaW9uOiAnMS4wLjAnCiAgfSk7Cn0pOwoKYXBwLnBvc3QoJy9hcGkvZXhlY3V0ZScsIGFzeW5jIChyZXEsIHJlcykgPT4gewogIHRyeSB7CiAgICBjb25zdCB7IGFwaV9uYW1lLCBtZXRob2QsIHBhdGgsIGRhdGEgfSA9IHJlcS5ib2R5OwogICAgCiAgICBpZiAoYXBpX25hbWUgIT09ICdnbGlkZS1hcGktdjEnKSB7CiAgICAgIHJldHVybiByZXMuc3RhdHVzKDQwMCkuanNvbih7IGVycm9yOiAnSW52YWxpZCBBUEkgbmFtZScgfSk7CiAgICB9CiAgICAKICAgIGNvbnN0IHJlc3BvbnNlID0gYXdhaXQgYXhpb3MoewogICAgICBtZXRob2Q6IG1ldGhvZCB8fCAnUE9TVCcsCiAgICAgIHVybDogcHJvY2Vzcy5lbnYuQVBJXzFfQkFTRV9VUkwgKyBwYXRoLAogICAgICBoZWFkZXJzOiB7CiAgICAgICAgJ0F1dGhvcml6YXRpb24nOiBwcm9jZXNzLmVudi5BUElfMV9IRUFERVJfQVVUSE9SSVpBVElPTiwKICAgICAgICAnQ29udGVudC1UeXBlJzogJ2FwcGxpY2F0aW9uL2pzb24nCiAgICAgIH0sCiAgICAgIGRhdGE6IGRhdGEKICAgIH0pOwogICAgCiAgICByZXMuanNvbihyZXNwb25zZS5kYXRhKTsKICB9IGNhdGNoIChlcnJvcikgewogICAgcmVzLnN0YXR1cyg1MDApLmpzb24oeyAKICAgICAgZXJyb3I6IGVycm9yLm1lc3NhZ2UsCiAgICAgIGRldGFpbHM6IGVycm9yLnJlc3BvbnNlPy5kYXRhIAogICAgfSk7CiAgfQp9KTsKCmFwcC5saXN0ZW4ocG9ydCwgKCkgPT4gewogIGNvbnNvbGUubG9nKCdHbGlkZSBBUEkgR2F0ZXdheSBydW5uaW5nIG9uIHBvcnQgJyArIHBvcnQpOwp9KTs=' | base64 -d > index.js &&
      
      npm install &&
      node index.js
      "
    ports:
      - "7777:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GLIDE_API_KEY=bcc7a00b-6919-47e1-8724-30999251a866
      - GLIDE_APP_ID=KyQIgjT4O1JsARXgkzsv
      - API_1_NAME=glide-api-v1
      - API_1_BASE_URL=https://api.glideapp.io/api/function
      - API_1_HEADER_AUTHORIZATION=Bearer bcc7a00b-6919-47e1-8724-30999251a866
      - CORS_ORIGIN=*
      - RATE_LIMIT_WINDOW=15
      - RATE_LIMIT_MAX=100
    networks:
      - glide-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  glide-network:
    driver: bridge