version: '3.8'

services:
  glide-api-gateway:
    image: node:18-alpine
    container_name: glide-api-gateway
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "
      apk add --no-cache curl wget &&
      cat > package.json << 'EOF'
      {
        \"name\": \"glide-api-gateway\",
        \"version\": \"1.0.0\",
        \"description\": \"MCP API Gateway for Glide API\",
        \"main\": \"index.js\",
        \"scripts\": {
          \"start\": \"node index.js\"
        },
        \"dependencies\": {
          \"express\": \"^4.18.2\",
          \"cors\": \"^2.8.5\",
          \"express-rate-limit\": \"^6.7.0\",
          \"axios\": \"^1.4.0\"
        }
      }
      EOF
      npm install &&
      node index.js
      "
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GLIDE_API_KEY=bcc7a00b-6919-47e1-8724-30999251a866
      - GLIDE_APP_ID=KyQIgjT4O1JsARXgkzsv
      - API_1_NAME=glide-api-v1
      - API_1_SWAGGER_URL=file:///app/glide-api-v1-openapi.json
      - API_1_BASE_URL=https://api.glideapp.io/api/function
      - API_1_HEADER_AUTHORIZATION=Bearer bcc7a00b-6919-47e1-8724-30999251a866
      - API_1_HEADER_CONTENT_TYPE=application/json
      - CORS_ORIGIN=*
      - RATE_LIMIT_WINDOW=15
      - RATE_LIMIT_MAX=100
    volumes:
      - ./index.js:/app/index.js:ro
      - ./http-server.js:/app/http-server.js:ro
      - ./glide-api-v1-openapi.json:/app/glide-api-v1-openapi.json:ro
    networks:
      - glide-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  glide-network:
    driver: bridge